### ISSUE TITLE
Add a convention to issue

### ISSUE THREAD

**Issue by GeraudFabien** [Microsoft/xaml-standard#152]
**Problem**
Eg: My problem is normal binding is slow
**Solution**
Eg: Making a new kind of binding. Using compile binding.....
**Exemple**
`my code`
**Solution drawback**
**Plateform or framework**

**Comment by markrendle** [comment]
How about this?

### When creating an issue, please use the following template as a guide.

### Which specific aspect of XAML Standard have you misunderstood?

- [ ] I think it's the XAML Specification
- [ ] I think it's WPF, UWP, Xamarin.Forms, or some other XAML-based UI framework
- [ ] I think it's one of those Design Language thingies like Material or Fluent
- [ ] I think it's going to ultimately have every control ever created just dumped into it, and I can get the ones I need (DataGrid!) dumped in sooner by creating multiple issues about all of them.

### How angry are you about Silverlight, five years on?
- [ ] Really angry. :rage1: 
- [ ] Really, really angry. :rage2: 
- [ ] I am consumed with hatred and poisoned by regret. :rage3:
- [ ] Meh, I'm over it. LOL NOT REALLY I'M STILL SPITTING CHIPS. :rage4:

### What percentage of the effort are you willing to accept in order to keep your projects up-to-date?
- [ ] Less than 1%.
- [ ] 0%

**Comment by Mike-EEE** [comment]
You forgot a calendar control, @markrendle.

![image](https://cloud.githubusercontent.com/assets/2931376/26358309/25e9c4c2-3fa0-11e7-9e18-4bc0de3e82df.png)

**Comment by insinfo** [comment]
That was funny

**Comment by Odonno** [comment]
I think it went too far. The point I wanted to say about this issue is that every issue will be different by nature and it will be really hard to introduce a specs format just right now.

Anyway, I think the real value will be contained in the markdown file and laterly on the source code that developers will be able to use and enjoy. But until then, every idea should matter based on the decision and the experience of developers.

So, I would like someone to close this issue or expose his arguments on this topic.

**Comment by birbilis** [comment]
Would like to see XSD for the spec or some extension of it

**Comment by GeraudFabien** [comment]
The goal is not to take all the issue. But to help people to make a new issue. I badly name it. What I wanted was more a base template more than a convention. It also may help to aggregate information and a quiker approach to read issue. https://github.com/dotnet/csharplang/blob/master/proposals/proposal-template.md

**Comment by Mike-EEE** [comment]
Good attempt, @GeraudFabien.  I sense there is a bit of a language barrier as well so we shouldn't be so rough on you. 😄  👼

**Comment by birbilis** [comment]
Would be nice if GitHub allowed maintainer of a repo to define a template/boilerplate for new issues

**Comment by bartlannoeye** [comment]
@birbilis that's possible: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by markrendle** [comment]
@GeraudFabien Please don't think I was making a joke at your expense; that was not my intention, and I'm truly sorry if it seemed like that to you.

I used your suggestion as a way to make a point about the variety of issues that I have been seeing on this repository, most of which seem to miss the point of XAML Standard in at least one of the ways I suggested.

In all seriousness, a proper template for issues could be an enormous help in reducing these sorts of posts, so I think it would be an excellent idea if done properly.

**Comment by GeraudFabien** [comment]
@markrendle i didn't thinks of it that way.
I know when i write this issue about the diversity of case who cannot be handle by one only template without making the process of making a new issue too heavy. I see convention more as best practice thant a rule. So the issue is closer to a template base thant a real convention in the usual meaning. 

In fact i feel weird that MS didn't make a "Contribute to XAML Standart" (Like https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md but adapt to language specification repository) where they explain what XAML standart is exactly and they advice. Sometime i feel like i'm on System.Ben repository. There is no Gitter. The projet lack of arbitrary Goal just to get an idea of what they expect. MS have experience about building XAML Spec (WPF, UWP, XAMARIN.Form) I at least expected a list of all the problem to avoid when making a new Control/Panel/... .

**Comment by birbilis** [comment]
Or maybe they have an idea of what it should be, but they want to gather feedback and shape it on the go. There is no need to involve the community else, could leave XAML in the state it was, broken in multiple pieces

**Comment by harinikmsft** [comment]
Done! Thanks for the feedback. We now have an issue template that should help with some guidance on what we are looking for and how you can position what you are filing in a way that will be useful in evolving the standard!

**Comment by dotMorten** [comment]
@harinikmsft On comment on the template: You're asking us to label the issues, but we don't have access to adding labels.

**Comment by harinikmsft** [comment]
Ah, I see. Updated the template. Thanks @dotMorten. 

`<Please excuse github noob />`
